name = "crdt-server"
main = "src/room.mjs"
compatibility_date = "2022-11-08"
account_id = "ACCOUNT_ID"

[durable_objects]
bindings = [
  { name = "rooms", class_name = "Room" },
]

# Indicate that you want the Room class to be callable as Durable Objects.
[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Room"]
